version: '3.8'
services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: nextbudget-postgres
    restart: always
    environment:
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=admin
      - POSTGRESQL_DATABASE=nextbudget
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/bitnami/postgresql

volumes:
  pg_data:
    driver: local
